### ISSUE TITLE
There was a problem installing LTI

### ISSUE THREAD

**Issue by a00110110** [microsoft/Learn-LTI#166]
Hello
I got an error when installing LTI. I have reinstalled it several times. Every time I installed it to the 10th step, there would be a problem. It seems to be a bug. How can I solve it?

First stage
![LTI](https://user-images.githubusercontent.com/36460921/144030836-bdff2aea-61e9-4f68-8137-9a612774593e.png)
[Log-30-11-2021-09-55-08.log](https://github.com/microsoft/Learn-LTI/files/7624980/Log-30-11-2021-09-55-08.log)
[Transcript-30-11-2021-09-55-08.log](https://github.com/microsoft/Learn-LTI/files/7624981/Transcript-30-11-2021-09-55-08.log)

second stage
I deleted all resource groups and all resources on Azure, and after redeploying LTI, the following problems occurred in the sixth step of deployment:

![LTI_2](https://user-images.githubusercontent.com/36460921/144034747-01dc2e03-29e9-4ef3-aa83-685db1d094a9.png)
[Log-30-11-2021-10-41-49.log](https://github.com/microsoft/Learn-LTI/files/7625141/Log-30-11-2021-10-41-49.log)
[Transcript-30-11-2021-10-41-49.log](https://github.com/microsoft/Learn-LTI/files/7625144/Transcript-30-11-2021-10-41-49.log)

**Comment by leestott** [comment]
So the error looks like you have NOT installed the prerequisites of .NETcore SDK or the version you have is less than 2.0.3 the latest version is 3.1 simply download and install it using the link below.. Please ensure you have all the other items also.

see https://github.com/microsoft/Learn-LTI/blob/main/docs/DEPLOYMENT_GUIDE.md

To begin, you will need:

Prerequisites
To begin, you will need:

Azure CLI
DotNet Core SDK
Node.js
Powershell
Git
An Azure subscription

See https://github.com/microsoft/Learn-LTI/blob/main/docs/DEPLOYMENT_GUIDE.md

Please follow the guide to ensure you delete your resources and redeploy https://github.com/microsoft/Learn-LTI/blob/main/docs/TROUBLESHOOTING.md

Again if you look at closed issues this issue is if you have not installed at the prerequirements 

Typical issue is people NOT installing .NETCORE SDK please ensure you have installed all the prerequirements and restarted the machine https://github.com/microsoft/Learn-LTI/issues?q=install+error

**Comment by leestott** [comment]
Your initial log had this error which indicates the wrong SDK being installed for .NET Core Please ensure you delete all resources using the cleanup script and ensure the resource group is deleted. 

???? .NET 6.0!
---------------------
SDK ??: 6.0.100

??
---------
.NET ?????????,??????????????? Microsoft ??,??????????????????,??????????,? DOTNET_CLI_TELEMETRY_OPTOUT ??????? '1' ? 'true' ???

?????? .NET CLI ???????: https://aka.ms/dotnet-cli-telemetry

----------------
??? ASP.NET Core HTTPS ?????
??????,??? 'dotnet dev-certs https --trust' (?? Windows ? macOS )?
???? HTTPS: https://aka.ms/dotnet-https
----------------
?????????: https://aka.ms/dotnet-hello-world
??????: https://aka.ms/dotnet-whats-new
????: https://aka.ms/dotnet-docs
? GitHub ?????????: https://github.com/dotnet/core
Use 'dotnet --help' ??????????: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
  ??????????...

**Comment by leestott** [comment]
@a00110110  I will close this issue as its a known issue of not installing the prerequisites if you need any more assistance please reopen the issue

**Comment by leestott** [comment]
@pfurgal5 Thanks for the comment made this is correct its the .NET Core SDK https://dotnet.microsoft.com/en-us/download/dotnet/3.1 

I have updated the docs to reflect this.

**Comment by leestott** [comment]
> Your initial log had this error which indicates the wrong SDK being installed for .NET Core Please ensure you delete all resources using the cleanup script and ensure the resource group is deleted.
> 
> ## ???? .NET 6.0!
> @a00110110
> 
> Error in the log
> 
> SDK ??: 6.0.100
> 
> ## ??
> .NET ?????????,??????????????? Microsoft ??,??????????????????,??????????,? DOTNET_CLI_TELEMETRY_OPTOUT ??????? '1' ? 'true' ???
> 
> ?????? .NET CLI ???????: https://aka.ms/dotnet-cli-telemetry
> 
> ## ??? ASP.NET Core HTTPS ?????
> ??????,??? 'dotnet dev-certs https --trust' (?? Windows ? macOS )?
> ???? HTTPS: https://aka.ms/dotnet-https
> ## ?????????: https://aka.ms/dotnet-hello-world
> ??????: https://aka.ms/dotnet-whats-new
> ????: https://aka.ms/dotnet-docs
> ? GitHub ?????????: https://github.com/dotnet/core
> Use 'dotnet --help' ??????????: https://aka.ms/dotnet-cli
> ??????????...

Please ensure you download and install the .NET Core SDK current version is 3.1 see https://dotnet.microsoft.com/en-us/download/dotnet/3.1
