### ISSUE TITLE
Ms learn LTI deployment stuck on step 12

### ISSUE THREAD

**Issue by elyes997** [microsoft/Learn-LTI#183]
Hi everyone,

I'm facing a problem with the deployment og Ms Learn LTI, it's stuck on step 12

Below a screenshot of the error.

I'm wondering if anyone has passed by this issue.

![image](https://user-images.githubusercontent.com/103292699/162547426-39c825fa-ea04-4965-918c-8b4402d163ba.png)

**Comment by maitreeleekha** [comment]
Can you please try this:
1. Go to the `Learn-LTI/client/` folder and delete the `node_modules` folder present there
2. Now while inside the `Learn-LTI/client/` folder, run the command: `npm install`. This may take some time to run, but should run successfully; if it fails please share the same error here.
3. Once the above command runs successfully, please try to run the deployment script again following the installation guide.

**Comment by elyes997** [comment]
I have followed the steps above but unfortunatly , it keep stucked in the same step , here a screeshot below: 

![image](https://user-images.githubusercontent.com/103292699/163816431-4b646526-0fea-42c7-b1e0-9605fa1f2e0b.png)

**Comment by maitreeleekha** [comment]
I see. Can also please also try to use the code before the recent PR merge ([https://github.com/microsoft/Learn-LTI/commit/ab57132792b2ead43e808a9174d16bb29e14293b](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FLearn-LTI%2Fcommit%2Fab57132792b2ead43e808a9174d16bb29e14293b&data=05%7C01%7CMaitree.Leekha%40microsoft.com%7C967740bf7f7c46d6a95408da213e896d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637858849875316011%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FvHNMntbi8FkfZ7kk2J3f4B6rdJfcniny4wEhZOzwfA%3D&reserved=0))? I had tested these updates on my end and they seemed to be working, just want to ensure if it's something with the recent change that this issue is happening?

 

Can you try to check out the code from this commit: [https://github.com/microsoft/Learn-LTI/commit/de5b75f308fd76fe363927d3fd19ec7e154f862e](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FLearn-LTI%2Fcommit%2Fde5b75f308fd76fe363927d3fd19ec7e154f862e&data=05%7C01%7CMaitree.Leekha%40microsoft.com%7C967740bf7f7c46d6a95408da213e896d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637858849875316011%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GcANc4UwZCFuKddVyHhKEHDlsvuABd3N9Y59khNLiUQ%3D&reserved=0) (i.e. before my recent PR merge) and try to deploy a new instance?

**Comment by leestott** [comment]
@elyes997  this looks like a issue with the Node Installation on the machine. 

Before anyone spends to much time debugging this problem, most of the time it can be resolved by deleting node_modules and reinstalling the packages.

Uninstalling the Node.js
Clear the npm cache by running the following command in your terminal.
npm cache clean --force

Go to the windows control panel and click on Uninstall a program, select Node.js and click on uninstall tab to uninstall the node and npm successfully.

Restart your system.

Verify if node.js and npm are completely uninstalled from your system using:

node -v

If the above command prints command not found then you’re successfully uninstalled, otherwise look into the below directories and remove the contents manually.

C:\Program Files (x86)\Nodejs
C:\Program Files\Nodejs
C:\Users\{User}\AppData\Roaming\npm (or %appdata%\npm)
C:\Users\{User}\AppData\Roaming\npm-cache (or %appdata%\npm-cache)
You can also learn, [How to uninstall node and npm from macos](https://reactgo.com/uninstall-node-npm-from-macos/).

To Install:
If a lockfile exists you might use
yarn install --frozen-lockfile

or
npm ci

if not then

yarn install
or
npm i

Ensure that all the prerequisites are installed and ensure the user does a reboot/restart of the machine to ensure environmental variables are updated

**Comment by leestott** [comment]
Just a clarification, scripts use npm and not yarn(as mentioned in thread).

Next Troubleshoot steps :

1. Check if the you have cleared the node modules properly.

2. Check version of the node and npm being used.  The one used in dev testing and our validation is Node : 12.21.0, npm : 6.14.11. 

If your still facing issues please use these versions.

**Comment by Combatchuck** [comment]
Is the Azure CLI supported? I get the same error when I try.

**Comment by maitreeleekha** [comment]
So the error is occurring in the step "Install Client" where we are running the command `npm run build` on the client app (line 147 in the file https://github.com/microsoft/Learn-LTI/blob/main/deployment/Install-Client.ps1) - this would also be the case if you run the `npm run build` command on the client folder outside of the deployment scripts

so if deleting the node_modules folder did not help, can we also try:

1. (i) `Deleting the package-lock.json + node_modules`; (ii) then run `npm install` on the client folder; (iii) then run `npm run build` on the client folder; see if this works/fails?
2. If 1. does not work- (i) on the client folder run `npm install -g react-scripts`; (ii) then run `npm run build` on the client folder

**Comment by maitreeleekha** [comment]
Update: The issue was due to node version being old on the user's machine (~`8.*`). Upgrading node version resolved the isue.

**Comment by maitreeleekha** [comment]
@leestott I think we can mark this one resolved
