### ISSUE TITLE
LTI Learn Integration on Moodle Issue 

### ISSUE THREAD

**Issue by ilyessennaceur** [microsoft/Learn-LTI#194]
# If this is about an issue in the guides

**Describe the issue**

after deploying moodle on azure , i start working on deploying LTI Learn on Azure too.
When integrating MS Learn on moodle and trying to configure Educator Registration. i face this error message : LTI Application does not load error: {'Message':'Could not validate request'} .
i tryed to solve this problem with Checking if i have a valid 3rd Party Signed SSL = OK
Checking  the Launch URL, and i make sure that all the fields are correctly filled while registering the tool and filling tool's platform registration page = OK 
Checking the Azure Function/Azure Logs = OK

**LMS (please complete the following information):**
 - Platfrom: [Moodle on Azure deployed ]
 - Version [3.8]
 - Installation [Managed Service SaaS]

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 ]
 - Browser [windows Edge]

**Comment by leestott** [comment]
LTI Application does not load error: {"Message":"Could not validate nonce."}
If you receive a browser message: {"Message":"Could not validate nonce."}

We have seen this is an intermittent issue, it usually happens if the user is trying to replay an old call or if the nonce and state value don't match. If the user simply refreshes the browser the page will load.

LTI Application does not load error: {"Message":"Could not validate request"}
This issue is typically related to one of the following:

Check if you have a valid 3rd Party Signed SSL. This services requires a valid 3rd party SSL certificate, self signed SSL certificates are not valid. Please ensure your service is using https:// with a valid SSL certification.
Check the Launch URL, please make sure that all the fields are correctly filled while registering the tool and filling tool's platform registration page. See https://github.com/microsoft/Learn-LTI/blob/main/docs/CONFIGURATION_GUIDE.md
Check the Azure Function/Azure Logs see https://github.com/microsoft/Learn-LTI/blob/main/docs/TROUBLESHOOTING.md#azure-functions-tracing

**Comment by leestott** [comment]
@ilyessennaceur closing as no updates since Jun

**Comment by leestott** [comment]
Problem was successfully resolved after deploying Moodle on Azure with the version 4.0.0 and enabling secure SSL
