### ISSUE TITLE
Error with basic installation

### ISSUE THREAD

**Issue by arnoldvilleneuve** [microsoft/Learn-LTI#202]
# Bug
**Describe the bug**
The error occurs during the RUN.BAT / deploy.ps1 phase. The Resource Group is successfully created and many of the resources are deployed before it fails. I tried two different Subscriptions and three different regions on the approved list. The error message told me to report it to github. 

Looking forward to actually getting this running. 

Error Message

43.2075","pairedRegion":"","physicalLocation":"Rio","regionCategory":"Other","regionType":"Physical"},"name":"brazilsoutheast","regionalDisplayName":"(South America) Brazil Southeast","subscriptionId":null}]
[ 8/28/2022 3:27:52 AM ] - [INFO] - User Provided Location Name: canadacentral
[ 8/28/2022 3:27:52 AM ] - [INFO] - Creating AAD App with Name: MS-Learn-One-Tool-App
[ 8/28/2022 3:27:54 AM ] - [INFO] - Updating Identifier URI's in AAD App to: [ api://f2610019-83da-43f1-8d8b-77d9d0a4e3ac ]
[ 8/28/2022 3:27:55 AM ] - [INFO] - Updating App so as to add MS Graph -> User Profile -> Read Permissions to the AAD App
[ 8/28/2022 3:27:58 AM ] - [INFO] - Creating Resource Group with Name: MSLearnOne at Location: canadacentral
[ 8/28/2022 3:28:01 AM ] - [INFO] - Deploying ARM Template to Azure inside ResourceGroup: MSLearnOne with DeploymentName: Deployment-28-08-2022-03-27-25, TemplateFile: azuredeploy.json, AppClientId: f2610019-83da-43f1-8d8b-77d9d0a4e3ac, IdentifiedURI: api://f2610019-83da-43f1-8d8b-77d9d0a4e3ac
[ 8/28/2022 3:29:42 AM ] - [ERROR] - Exception.Message [ Encountered an Error while deploying to Azure ]
[ 8/28/2022 3:29:42 AM ] - [ERROR] - Exception.Type    [ System.Management.Automation.RuntimeException ]
[ 8/28/2022 3:29:42 AM ] - [ERROR] - Error occurred while executing the Script. Please report the bug on Github (along with Error Message & Logs)

**To Reproduce**
1. Run the Run.bat program using all of the defaults. 

**Expected behavior**
The installation does not complete and I am not provided with a URL for the configuration information, which is what is expected. 

**Additional context**
I am the Azure Global Administrator and owner of all of the Subscriptions. I am just trying to follow the installation instructions. 

Appreciate all of the help you can provide. MS Learn is a great learning platform and I would like to provide integration for companies that are interested in leveraging it.

**Comment by leestott** [comment]
If the implementation failed you need to remove the resource group and all associated resources first before follow the troubleshooting guide https://github.com/microsoft/Learn-LTI/blob/main/docs/TROUBLESHOOTING.md

If you simply try to reinstall before removal you will get errors. SO PLEASE REMOVE ALL INSTALLED SERVICES

The root cause of the issues looks like you simply didn't have the prerequisites installed before doing the initial install. See https://github.com/microsoft/Learn-LTI/blob/main/docs/DEPLOYMENT_GUIDE.md

You need!

[Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest?WT.mc_id=learnlti-github-cxa)
We currently recommend using Microsoft CLI version 2.27. The most recent version is of Azure CLI has deprecated commands in use which will be addressed later.
[DotNet Core SDK .NET Core 3.1](https://dotnet.microsoft.com/download/dotnet/3.1?WT.mc_id=learnlti-github-cxa)
[Node.js](https://nodejs.org/en/download/)
[Powershell](https://docs.microsoft.com/powershell/scripting/install/installing-powershell?view=powershell-7?WT.mc_id=learnlti-github-cxa)
[Git](https://git-scm.com/downloads)
An Azure subscription

**Comment by arnoldvilleneuve** [comment]
Thank you Lee. Then main issue appears to be the version of the Azure CLI. I removed the Azure CLI and installed the 2.27 version. The installation worked as described. Thank you for developing such a great project.

**Comment by arnoldvilleneuve** [comment]
Thank you Lee. 
I have all of the prerequesits listed below however I will go back and verify Azure CLI. 
I will confirm a successful installation. 
Thank you.  
Arnold Villeneuve 613-833-0984 

    On Tuesday, August 30, 2022 at 04:58:49 a.m. EDT, Lee Stott ***@***.***> wrote:  
 
 


If the implementation failed you need to remove the resource group and all associated resources first before follow the troubleshooting guide https://github.com/microsoft/Learn-LTI/blob/main/docs/TROUBLESHOOTING.md

If you simply try to reinstall before removal you will get errors. SO PLEASE REMOVE ALL INSTALLED SERVICES

The root cause of the issues looks like you simply didn't have the prerequisites installed before doing the initial install. See https://github.com/microsoft/Learn-LTI/blob/main/docs/DEPLOYMENT_GUIDE.md

You need!

Azure CLI
We currently recommend using Microsoft CLI version 2.27. The most recent version is of Azure CLI has deprecated commands in use which will be addressed later.
DotNet Core SDK .NET Core 3.1
Node.js
Powershell
Git
An Azure subscription
