### ISSUE TITLE
Parent Resource Not Found

### ISSUE THREAD

**Issue by skmckenFVSD** [microsoft/Learn-LTI#66]
# Bug
**Parent Resource Not Found**
Deployment failing in Step 8 - Creating Resources in Azure within PowerShell.

**To Reproduce**
1. run.bat in PowerShell
2. Deployment failed. Correlation ID: c7ac44aa-eb0a-4867-8e91-0d073dc2e668. {
  "error": {
    "code": "ParentResourceNotFound",
    "message": "Can not perform requested operation on nested resource. Parent resource 'kv-73i32pmz3' not found."
  }
}

**Additional context**
This occurred after pulling Main to fix the HTTPSConnectionPool which was corrected in the azuredeploy.json

**Comment by adbindal** [comment]
Hi @skmckenFVSD,

Thanks a lot for reporting the issue. 

## Probable Theory
Based on the current information, unfortunately, the only thing I could interpret is that the ARM template seems to have faced some issue in deploying the `KeyVault` resource in your chosen deployment. You could consider trying to re-deploy the same RG/Identity/AppName combination by simply re-executing `run.bat` or deploy a new RG inside a different region than the one tried above.

## Troubleshooting Tips
In order to understand the issue in more detail, one way could be to go through the deployment details which could be accessed via Azure Portal. 
> Go to Azure Portal -> Choose appropriate Subscription -> Select Resource Groups blade from Left Rail -> Choose appropriate Resource Group -> Select Deployments Blade from Left Rail.
---
In case none of the above help you move in the correct direction, I'd request you to please reach out to us at learnlti@microsoft.com in order to better understand your issue and provide support from our end.

**Comment by skmckenFVSD** [comment]
I re-deployed to westus with no issue. Previous deployment was to canadacentral.
